name: Mise à jour quotidienne de flashbriefing.json

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Récupération du dépôt
      uses: actions/checkout@v3

    - name: Installation de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Installer les dépendances
      run: pip install requests beautifulsoup4

    - name: Exécuter le script
      run: python safran_script.py

    - name: Commit et push des changements
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add flashbriefing.json
        git commit -m "Mise à jour automatique du flashbriefing.json"
        git push
